# Generated by Django 6.1.1 on 2026-09-25 03:57

import apps.accounts.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'доступ к панели',
                'permissions': [('manage_users', 'Пользователи и роли'), ('manage_data', 'Данные и источники'), ('manage_tickets', 'Обращения'), ('manage_content', 'Глоссарий и методика')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('email', models.EmailField(help_text='Используется для входа в систему и служебных писем', max_length=254, unique=True, verbose_name='адрес электронной почты')),
                ('full_name', models.CharField(help_text='Отображается в интерфейсе и в колонтитулах выгружаемых отчётов', max_length=180, verbose_name='фамилия, имя, отчество')),
                ('organization', models.CharField(blank=True, help_text='Место работы или учёбы; заполняется по желанию', max_length=180, verbose_name='организация')),
                ('position', models.CharField(blank=True, max_length=180, verbose_name='должность')),
                ('is_active', models.BooleanField(default=True, help_text='Снятие признака блокирует вход без удаления данных пользователя', verbose_name='учётная запись активна')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя активность')),
                ('updates_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='новое просмотрено')),
                ('session_version', models.PositiveIntegerField(default=0, verbose_name='версия сеансов')),
                ('pending_email', models.EmailField(blank=True, max_length=254, verbose_name='новый адрес, ждёт подтверждения')),
                ('totp_secret', models.CharField(blank=True, max_length=64, verbose_name='ключ кодов входа')),
                ('totp_enabled_at', models.DateTimeField(blank=True, null=True, verbose_name='вход с кодом включён')),
                ('totp_last_step', models.BigIntegerField(default=0, verbose_name='последний принятый шаг')),
                ('recovery_codes', models.JSONField(blank=True, default=list, verbose_name='резервные коды (хэши)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('region', models.ForeignKey(blank=True, help_text='С него открываются главная страница и кабинет', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.territory', verbose_name='мой регион')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['full_name'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
