# Generated by Django 6.1.1 on 2026-09-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Используется для входа на сайт и служебных писем', max_length=254, unique=True, verbose_name='адрес электронной почты'),
        ),
    ]
