# Generated by Django 6.1.1 on 2026-09-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_organization_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='согласие на обработку дано'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_revision',
            field=models.DateField(blank=True, null=True, verbose_name='редакция согласия'),
        ),
    ]
