# Generated by Django 6.1.1 on 2026-09-23 16:57

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodologySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=100, help_text='Меньшее значение — выше в списке', verbose_name='порядок отображения')),
                ('code', models.SlugField(help_text='Устойчивый идентификатор для ссылок со страниц анализа', max_length=60, unique=True, verbose_name='код раздела')),
                ('block', models.CharField(choices=[('data', 'Подготовка данных'), ('reading', 'Карта, места и оценки'), ('normalization', 'Нормализация'), ('weights', 'Взвешивание'), ('aggregation', 'Агрегация'), ('statistics', 'Статистические методы'), ('inequality', 'Неравенство и конвергенция'), ('spatial', 'Пространственный анализ'), ('quality', 'Качество данных и расчётов')], db_index=True, default='statistics', max_length=20, verbose_name='блок')),
                ('tool_url_name', models.CharField(blank=True, help_text='Имя маршрута страницы анализа, например analytics:inequality', max_length=80, verbose_name='маршрут инструмента')),
                ('references', models.JSONField(blank=True, default=list, help_text='Библиографические ссылки, обосновывающие метод', verbose_name='источники')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='показывать на сайте')),
            ],
            options={
                'verbose_name': 'раздел методологии',
                'verbose_name_plural': 'разделы методологии',
                'ordering': ['block', 'display_order', 'code'],
                'indexes': [models.Index(fields=['block', 'display_order'], name='methodology_block_order_idx')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='адрес')),
                ('category', models.CharField(choices=[('statistics', 'Статистика'), ('economy', 'Региональная экономика'), ('method', 'Методы анализа'), ('data', 'Работа с данными'), ('system', 'Обозначения системы')], db_index=True, default='statistics', max_length=20, verbose_name='раздел')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='показывать на сайте')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossary_terms', to='catalog.indicator', verbose_name='показатель каталога')),
                ('related_terms', models.ManyToManyField(blank=True, to='content.glossaryterm', verbose_name='смежные термины')),
                ('methodology_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='content.methodologysection', verbose_name='раздел методологии')),
            ],
            options={
                'verbose_name': 'термин глоссария',
                'verbose_name_plural': 'глоссарий',
                'ordering': ['slug'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GlossaryTermTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('term', models.CharField(db_index=True, max_length=200, verbose_name='термин')),
                ('short_definition', models.CharField(help_text='Одно предложение — показывается во всплывающей подсказке', max_length=300, verbose_name='краткое определение')),
                ('definition', models.TextField(blank=True, verbose_name='определение')),
                ('synonyms', models.CharField(blank=True, help_text='Через запятую; используются поиском по глоссарию', max_length=300, verbose_name='синонимы')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.glossaryterm')),
            ],
            options={
                'verbose_name': 'термин глоссария Translation',
                'db_table': 'content_glossaryterm_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_glossaryterm_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MethodologySectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('summary', models.CharField(blank=True, help_text='Одно предложение о том, что даёт метод', max_length=400, verbose_name='краткое описание')),
                ('formula', models.CharField(blank=True, help_text='Запись формулы в текстовом виде; показывается моноширинным шрифтом', max_length=300, verbose_name='формула')),
                ('body', models.TextField(blank=True, help_text='Обозначения, условия применимости, ограничения метода', verbose_name='изложение')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.methodologysection')),
            ],
            options={
                'verbose_name': 'раздел методологии Translation',
                'db_table': 'content_methodologysection_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('language_code', 'master'), name='content_methodologysection_translation_uniq_lang')],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
