# Generated by Django 6.1.1 on 2026-09-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='category',
            field=models.CharField(choices=[('statistics', 'Статистика'), ('economy', 'Региональная экономика'), ('method', 'Методы анализа'), ('data', 'Работа с данными'), ('system', 'Обозначения на сайте')], db_index=True, default='statistics', max_length=20, verbose_name='раздел'),
        ),
    ]
