# Generated by Django 6.1.2 on 2026-10-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_glossary_category_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodologysectiontranslation',
            name='limitations',
            field=models.TextField(blank=True, help_text='Два-три ограничения метода, по одному предложению в строке', verbose_name='ограничения'),
        ),
        migrations.AlterField(
            model_name='methodologysectiontranslation',
            name='body',
            field=models.TextField(blank=True, help_text='Обозначения и условия применимости, до 120 слов', verbose_name='изложение'),
        ),
        migrations.AlterField(
            model_name='methodologysectiontranslation',
            name='formula',
            field=models.TextField(blank=True, help_text='Строка — одна формула: подпись и запись MathML (<math>…</math>); строка без MathML показывается моноширинным шрифтом', verbose_name='формула'),
        ),
    ]
