# Generated by Django 6.1.2 on 2026-10-07 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMiss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='запрос')),
                ('language', models.CharField(max_length=8, verbose_name='язык')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='когда')),
            ],
            options={
                'verbose_name': 'запрос без ответа',
                'verbose_name_plural': 'запросы без ответа',
                'ordering': ['-created_at'],
            },
        ),
    ]
