"""
Запросы представлений к складу DuckDB.

Значения передаются параметрами, имена столбцов — только из белых списков.
"""

from __future__ import annotations

from .analysis import (
    district_directory,
    edition_activity,
    hidden_counts,
    largest_revisions,
    paired_years,
    region_directory,
    region_matrix,
    region_panel,
    revision_distribution,
    revision_summary,
    revision_trace,
    revision_triangle,
    revisions_by_section,
    revisions_by_series,
    revisions_by_year,
    series_covered_years,
    series_years,
)
from .common import (
    COUNTRY_CODE,
    LEVEL_COUNTRY,
    LEVEL_DISTRICT,
    LEVEL_REGION,
    MIN_YEAR_COVERAGE,
    REAL_BY_INDEX,
    REAL_BY_PRICES,
    REAL_BY_VOLUME,
    SUMMARY_CACHE_TTL,
    FeaturedSeries,
    FeaturedSet,
    FeaturedTheme,
    RealBasis,
    covered_years,
    featured_series,
    featured_set,
)
from .ranking import rank_history, rank_movers, ranked_years, ranking_table
from .series import (
    available_years,
    featured_snapshot,
    latest_values_matrix,
    series_editions,
    series_leaders,
    series_metadata,
    series_observations,
    series_ranked_panel,
    series_revisions,
    series_statistics,
    series_statistics_timeline,
    series_summary_map,
    series_timeline,
    series_timeline_multi,
    series_values,
    series_values_by_territory,
    series_vintages,
    year_counts,
)
from .summary import (
    build_metadata,
    coverage_distribution,
    observations_by_year,
    total_observations,
    warehouse_summary,
)
from .territory import (
    district_summary,
    territory_coverage,
    territory_positions,
    territory_profile,
    territory_values_for_series,
)

__all__ = [
    "COUNTRY_CODE",
    "LEVEL_COUNTRY",
    "LEVEL_DISTRICT",
    "LEVEL_REGION",
    "MIN_YEAR_COVERAGE",
    "REAL_BY_INDEX",
    "REAL_BY_PRICES",
    "REAL_BY_VOLUME",
    "SUMMARY_CACHE_TTL",
    "FeaturedSeries",
    "FeaturedSet",
    "FeaturedTheme",
    "RealBasis",
    "available_years",
    "build_metadata",
    "coverage_distribution",
    "covered_years",
    "district_directory",
    "district_summary",
    "edition_activity",
    "featured_series",
    "featured_set",
    "featured_snapshot",
    "hidden_counts",
    "largest_revisions",
    "latest_values_matrix",
    "observations_by_year",
    "paired_years",
    "rank_history",
    "rank_movers",
    "ranked_years",
    "ranking_table",
    "region_directory",
    "region_matrix",
    "region_panel",
    "revision_distribution",
    "revision_summary",
    "revision_trace",
    "revision_triangle",
    "revisions_by_section",
    "revisions_by_series",
    "revisions_by_year",
    "series_covered_years",
    "series_editions",
    "series_leaders",
    "series_metadata",
    "series_observations",
    "series_ranked_panel",
    "series_revisions",
    "series_statistics",
    "series_statistics_timeline",
    "series_summary_map",
    "series_timeline",
    "series_timeline_multi",
    "series_values",
    "series_values_by_territory",
    "series_vintages",
    "series_years",
    "territory_coverage",
    "territory_positions",
    "territory_profile",
    "territory_values_for_series",
    "total_observations",
    "warehouse_summary",
    "year_counts",
]
