# Generated by Django 6.1.1 on 2026-09-23 16:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('mode', models.CharField(choices=[('full', 'Полная сборка'), ('marts', 'Пересчёт витрин'), ('catalog', 'Синхронизация справочников')], default='full', max_length=16, verbose_name='режим')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('running', 'Выполняется'), ('success', 'Завершён успешно'), ('failed', 'Завершён с ошибкой'), ('cancelled', 'Прерван')], db_index=True, default='running', max_length=16, verbose_name='состояние')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='окончание')),
                ('duration_seconds', models.FloatField(blank=True, null=True, verbose_name='длительность, с')),
                ('source_path', models.CharField(blank=True, max_length=500, verbose_name='путь к исходному файлу')),
                ('source_checksum', models.CharField(blank=True, max_length=64, verbose_name='контрольная сумма источника')),
                ('observation_count', models.PositiveIntegerField(default=0, verbose_name='наблюдений загружено')),
                ('series_count', models.PositiveIntegerField(default=0, verbose_name='рядов')),
                ('revision_count', models.PositiveIntegerField(default=0, verbose_name='пересмотренных наблюдений')),
                ('break_count', models.PositiveIntegerField(default=0, verbose_name='выявлено разрывов')),
                ('statistics', models.JSONField(blank=True, default=dict, help_text='Профиль источника, распределение качества значений, длительность этапов', verbose_name='показатели сборки')),
                ('log', models.TextField(blank=True, verbose_name='журнал')),
                ('error_message', models.TextField(blank=True, verbose_name='сообщение об ошибке')),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etl_runs', to='catalog.datasetversion', verbose_name='версия набора данных')),
                ('started_by', models.ForeignKey(blank=True, help_text='Пусто, если сборка запущена из командной строки или по расписанию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_runs', to=settings.AUTH_USER_MODEL, verbose_name='запустил')),
            ],
            options={
                'verbose_name': 'запуск ETL',
                'verbose_name_plural': 'запуски ETL',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('check_type', models.CharField(choices=[('aggregate_mismatch', 'Расхождение суммы регионов с итогом'), ('sudden_jump', 'Резкое изменение значения'), ('gap', 'Разрыв в ряде наблюдений'), ('unit_inconsistency', 'Несогласованность единиц измерения'), ('status_outdated', 'Устаревшее состояние публикации')], db_index=True, max_length=32, verbose_name='тип проверки')),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка')], db_index=True, default='warning', max_length=10, verbose_name='уровень')),
                ('series_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='ключ ряда')),
                ('territory_code', models.CharField(blank=True, max_length=16, verbose_name='код территории')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год')),
                ('message', models.CharField(max_length=500, verbose_name='описание')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='подробности')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='warehouse.etlrun', verbose_name='запуск')),
            ],
            options={
                'verbose_name': 'проверка качества данных',
                'verbose_name_plural': 'проверки качества данных',
                'ordering': ['-created_at', 'severity'],
            },
        ),
        migrations.AddIndex(
            model_name='etlrun',
            index=models.Index(fields=['status', '-started_at'], name='etl_status_started_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualitycheck',
            index=models.Index(fields=['check_type', 'severity'], name='quality_type_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='dataqualitycheck',
            index=models.Index(fields=['series_key', 'year'], name='quality_series_year_idx'),
        ),
    ]
