# Generated by Django 6.1.1 on 2026-10-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etlrun',
            name='mode',
            field=models.CharField(choices=[('full', 'Полная сборка'), ('marts', 'Пересчёт витрин'), ('catalog', 'Синхронизация справочников'), ('candidate', 'Проверка новой версии набора')], default='full', max_length=16, verbose_name='режим'),
        ),
    ]
