# Generated by Django 6.1.1 on 2026-09-23 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('contact_name', models.CharField(max_length=180, verbose_name='имя отправителя')),
                ('contact_email', models.EmailField(db_index=True, max_length=254, verbose_name='адрес для ответа')),
                ('topic', models.CharField(choices=[('data_error', 'Ошибка в данных'), ('method', 'Вопрос по методике расчёта'), ('feature', 'Предложение по развитию'), ('bug', 'Неисправность в работе сайта'), ('access', 'Доступ и учётная запись'), ('cooperation', 'Сотрудничество и использование данных'), ('other', 'Другое')], db_index=True, default='other', max_length=20, verbose_name='тема')),
                ('subject', models.CharField(max_length=200, verbose_name='заголовок')),
                ('body', models.TextField(verbose_name='текст обращения')),
                ('status', models.CharField(choices=[('new', 'Ждёт ответа'), ('answered', 'Отвечено'), ('closed', 'Закрыто без ответа')], db_index=True, default='new', max_length=16, verbose_name='состояние')),
                ('page_url', models.CharField(blank=True, help_text='Адрес страницы, с которой отправлено обращение; заполняется автоматически', max_length=500, verbose_name='страница обращения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='адрес отправителя')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='клиент')),
                ('answer', models.TextField(blank=True, help_text='Уходит письмом на адрес для ответа', verbose_name='ответ')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='ответ написан')),
                ('answer_delivery', models.CharField(blank=True, choices=[('', 'Ответа нет'), ('sent', 'Доставлено'), ('failed', 'Не доставлено')], default='', max_length=8, verbose_name='доставка ответа')),
                ('answer_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='письмо принято почтовым узлом')),
                ('answer_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='попыток отправки')),
                ('answer_error', models.CharField(blank=True, max_length=500, verbose_name='причина отказа')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_tickets', to=settings.AUTH_USER_MODEL, verbose_name='ответил')),
                ('author', models.ForeignKey(blank=True, help_text='Пусто, если обращение оставлено без входа в систему', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ticket_status_time_idx')],
            },
        ),
    ]
