# Generated by Django 6.1.1 on 2026-09-24 15:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='код')),
                ('title_ru', models.CharField(max_length=300, verbose_name='название')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='название (англ.)')),
                ('publisher_ru', models.CharField(max_length=200, verbose_name='издатель')),
                ('publisher_en', models.CharField(blank=True, max_length=200, verbose_name='издатель (англ.)')),
                ('licence_ru', models.CharField(blank=True, max_length=300, verbose_name='условия использования')),
                ('licence_en', models.CharField(blank=True, max_length=300, verbose_name='условия использования (англ.)')),
                ('page_url', models.URLField(blank=True, max_length=500, verbose_name='страница источника')),
                ('check_every', models.DurationField(default=datetime.timedelta(days=1), verbose_name='проверять раз в')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='последняя проверка')),
                ('check_ok', models.BooleanField(default=True, verbose_name='проверка удалась')),
                ('check_error', models.TextField(blank=True, verbose_name='ошибка проверки')),
                ('running_since', models.DateTimeField(blank=True, null=True, verbose_name='сбор идёт с')),
            ],
            options={
                'verbose_name': 'источник данных',
                'verbose_name_plural': 'источники данных',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('code', models.CharField(help_text='«07-2026», «2026-03-06»', max_length=40, verbose_name='код выпуска')),
                ('title', models.CharField(max_length=200, verbose_name='выпуск')),
                ('reference_year', models.PositiveSmallIntegerField(verbose_name='год выпуска')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='опубликован')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='адрес')),
                ('file_name', models.CharField(max_length=255, verbose_name='имя файла')),
                ('archive_path', models.CharField(max_length=500, verbose_name='путь в архиве')),
                ('sha256', models.CharField(max_length=64, unique=True, verbose_name='SHA-256')),
                ('size_bytes', models.PositiveBigIntegerField(verbose_name='размер, байт')),
                ('remote_modified', models.DateTimeField(blank=True, null=True, verbose_name='изменён на сайте')),
                ('fetched_at', models.DateTimeField(verbose_name='получен')),
                ('status', models.CharField(choices=[('fetched', 'Получен'), ('parsed', 'Разобран'), ('failed', 'Ошибка разбора')], db_index=True, default='fetched', max_length=10, verbose_name='состояние')),
                ('parser_version', models.PositiveSmallIntegerField(default=0, verbose_name='версия разбора')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='разобран')),
                ('row_count', models.PositiveIntegerField(default=0, verbose_name='значений')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='отчёт о разборе')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Последний период по показателям и число изменённых значений', verbose_name='изменения к прежнему выпуску')),
                ('error', models.TextField(blank=True, verbose_name='ошибка разбора')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='sources.source', verbose_name='источник')),
            ],
            options={
                'verbose_name': 'выпуск источника',
                'verbose_name_plural': 'выпуски источников',
                'ordering': ['-reference_year', '-published_on', '-fetched_at'],
                'indexes': [models.Index(fields=['source', 'status'], name='release_source_status_idx')],
            },
        ),
    ]
