# Generated by Django 6.1.1 on 2026-09-23 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='пометка')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.indicator', verbose_name='показатель')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.series', verbose_name='ряд')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.territory', verbose_name='территория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'избранное',
                'verbose_name_plural': 'избранное',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('indicator__isnull', False), ('series__isnull', True), ('territory__isnull', True)), models.Q(('indicator__isnull', True), ('series__isnull', False), ('territory__isnull', True)), models.Q(('indicator__isnull', True), ('series__isnull', True), ('territory__isnull', False)), _connector='OR'), name='favorite_exactly_one_object'), models.UniqueConstraint(condition=models.Q(('indicator__isnull', False)), fields=('user', 'indicator'), name='favorite_unique_indicator'), models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('user', 'series'), name='favorite_unique_series'), models.UniqueConstraint(condition=models.Q(('territory__isnull', False)), fields=('user', 'territory'), name='favorite_unique_territory')],
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('title', models.CharField(max_length=160, verbose_name='название')),
                ('description', models.TextField(blank=True, help_text='Зачем сохранена выборка и на что обратить внимание при открытии', verbose_name='пояснение')),
                ('target', models.CharField(choices=[('map', 'Карта'), ('rankings', 'Рейтинг'), ('compare', 'Динамика и сравнение'), ('distribution', 'Распределение'), ('table', 'Таблица значений'), ('inequality', 'Неравенство'), ('convergence', 'Конвергенция'), ('correlation', 'Корреляции'), ('spatial', 'Пространственный анализ'), ('index-builder', 'Интегральные индексы'), ('revisions', 'Пересмотры статистики')], db_index=True, max_length=32, verbose_name='страница')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Строка запроса страницы в разобранном виде', verbose_name='параметры')),
                ('opened_count', models.PositiveIntegerField(default=0, verbose_name='число открытий')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='последнее открытие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'сохранённая выборка',
                'verbose_name_plural': 'сохранённые выборки',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='savedquery_user_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'title'), name='savedquery_unique_title_per_user')],
            },
        ),
    ]
