# Generated by Django 6.1.2 on 2026-10-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedquery',
            name='target',
            field=models.CharField(choices=[('map', 'Карта'), ('rankings', 'Рейтинг'), ('compare', 'Динамика'), ('distribution', 'Распределение'), ('table', 'Таблица'), ('inequality', 'Неравенство'), ('convergence', 'Конвергенция'), ('correlation', 'Корреляции'), ('spatial', 'Пространственный анализ'), ('index-builder', 'Интегральные индексы'), ('revisions', 'Пересмотры статистики')], db_index=True, max_length=32, verbose_name='страница'),
        ),
    ]
