# Generated by Django 6.1.1 on 2026-10-03 20:02

import apps.userdata.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='публичный идентификатор')),
                ('code', models.CharField(default=apps.userdata.models.new_code, max_length=12, unique=True, verbose_name='код в ключах рядов')),
                ('guest_key', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='отпечаток гостевого ключа')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='хранится до')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('source_title', models.CharField(blank=True, max_length=300, verbose_name='источник')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='адрес источника')),
                ('state', models.CharField(choices=[('draft', 'черновик'), ('ready', 'готов'), ('failed', 'не собран')], default='draft', max_length=10, verbose_name='состояние')),
                ('size_bytes', models.BigIntegerField(default=0, verbose_name='занятое место')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'набор пользователя',
                'verbose_name_plural': 'наборы пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('number', models.PositiveIntegerField(verbose_name='номер')),
                ('file_name', models.CharField(max_length=255, verbose_name='имя файла')),
                ('file_size', models.BigIntegerField(verbose_name='размер файла')),
                ('sha256', models.CharField(max_length=64, verbose_name='отпечаток SHA-256')),
                ('file_kind', models.CharField(max_length=16, verbose_name='вид файла')),
                ('recipe', models.JSONField(blank=True, default=dict, verbose_name='рецепт')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='отчёт')),
                ('parser_version', models.PositiveSmallIntegerField(default=1, verbose_name='редакция разборщика')),
                ('state', models.CharField(choices=[('uploaded', 'файл принят'), ('described', 'таблица описана'), ('building', 'собирается'), ('built', 'собран'), ('failed', 'не разобран')], default='uploaded', max_length=10, verbose_name='состояние')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('values_count', models.PositiveIntegerField(default=0, verbose_name='значений')),
                ('series_count', models.PositiveIntegerField(default=0, verbose_name='рядов')),
                ('regions_count', models.PositiveSmallIntegerField(default=0, verbose_name='субъектов')),
                ('first_year', models.SmallIntegerField(blank=True, null=True, verbose_name='первый год')),
                ('last_year', models.SmallIntegerField(blank=True, null=True, verbose_name='последний год')),
                ('data_file', models.CharField(blank=True, max_length=64, verbose_name='файл сборки')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='userdata.dataset', verbose_name='набор')),
            ],
            options={
                'verbose_name': 'версия набора',
                'verbose_name_plural': 'версии наборов',
                'ordering': ['dataset', '-number'],
            },
        ),
        migrations.CreateModel(
            name='DatasetSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, verbose_name='код ряда')),
                ('indicator', models.CharField(max_length=300, verbose_name='показатель в таблице')),
                ('title', models.CharField(max_length=300, verbose_name='название')),
                ('unit', models.CharField(blank=True, max_length=120, verbose_name='единица')),
                ('kind', models.CharField(blank=True, choices=[('sum', 'сумма'), ('relative', 'относительная величина')], max_length=10, verbose_name='вид величины')),
                ('polarity', models.CharField(choices=[('positive', 'рост — к лучшему'), ('negative', 'рост — к худшему'), ('neutral', 'без оценки')], default='neutral', max_length=10, verbose_name='направленность')),
                ('precision', models.PositiveSmallIntegerField(default=1, verbose_name='знаков после запятой')),
                ('slices', models.JSONField(blank=True, default=list, verbose_name='значения разрезов')),
                ('period', models.CharField(default='year:12', max_length=16, verbose_name='период года')),
                ('derived', models.CharField(blank=True, choices=[('', 'из таблицы'), ('per1000', 'на 1 000 жителей'), ('per100000', 'на 100 000 жителей'), ('perkm2', 'на км²')], default='', max_length=10, verbose_name='пересчёт')),
                ('base_code', models.CharField(blank=True, max_length=24, verbose_name='код исходного ряда')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('values_count', models.PositiveIntegerField(default=0, verbose_name='значений')),
                ('regions_count', models.PositiveSmallIntegerField(default=0, verbose_name='субъектов')),
                ('first_year', models.SmallIntegerField(blank=True, null=True, verbose_name='первый год')),
                ('last_year', models.SmallIntegerField(blank=True, null=True, verbose_name='последний год')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='userdata.datasetversion', verbose_name='версия')),
            ],
            options={
                'verbose_name': 'ряд набора',
                'verbose_name_plural': 'ряды наборов',
                'ordering': ['version', 'order'],
            },
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='userdata.datasetversion', verbose_name='текущая версия'),
        ),
        migrations.CreateModel(
            name='TerritoryLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Момент создания записи', verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Момент последнего изменения записи', verbose_name='изменено')),
                ('label_key', models.CharField(max_length=300, verbose_name='подпись для сравнения')),
                ('territory_code', models.CharField(max_length=16, verbose_name='территория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territory_labels', to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'запомненная подпись территории',
                'verbose_name_plural': 'запомненные подписи территорий',
            },
        ),
        migrations.AddConstraint(
            model_name='datasetversion',
            constraint=models.UniqueConstraint(fields=('dataset', 'number'), name='userdata_version_number'),
        ),
        migrations.AddConstraint(
            model_name='datasetseries',
            constraint=models.UniqueConstraint(fields=('version', 'code'), name='userdata_series_code'),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.CheckConstraint(condition=models.Q(('owner__isnull', False), models.Q(('guest_key', ''), _negated=True), _connector='OR'), name='userdata_dataset_has_owner'),
        ),
        migrations.AddConstraint(
            model_name='territorylabel',
            constraint=models.UniqueConstraint(fields=('owner', 'label_key'), name='userdata_label_per_owner'),
        ),
    ]
